//_id:610c1814e80f5d67414d3660 -> 24 characters
//12 bytes
//  4 bytes: timestamp -> so that insteading of sorting by time, we can sort by _id
//  3 bytes: machine identifier
//  2 bytes: process identifier
//  3 bytes: counter

//1 byte = 8 bits
// 2^8 = 256
// 2^24 (3 bytes counter)

//Driver -> MongoDB
//_id is generated by the driver
//mongoose is an abstraction over MongoDB Driver
//when we create object, mongoose talk to mongodb driver to generate _id

const mongoose = require("mongoose");

const id = new mongoose.Types.ObjectId();
console.log(id);
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid("1234");
console.log(isValid);
